# Generated by Django 5.1.6 on 2025-06-19 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('purchase', 'Purchase')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('consumption', models.FloatField(blank=True, help_text='kWh for electricity, m³ for water', null=True)),
                ('items', models.JSONField(blank=True, help_text='List of purchased items in JSON format', null=True)),
                ('original_image', models.ImageField(upload_to='bills/original/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bills/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
