# Generated by Django 5.1.6 on 2025-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='owner',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
