# Generated by Django 5.1.6 on 2025-08-28 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('purchase', 'Purchase'), ('bilan', 'Bilan')], max_length=20),
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('montant_actif', models.DecimalField(decimal_places=2, help_text='Montant actif du bilan', max_digits=15)),
                ('montant_passif', models.DecimalField(decimal_places=2, help_text='Montant passif du bilan', max_digits=15)),
                ('date_entree', models.DateField(help_text="Date d'entrée du bilan")),
                ('date_sortie', models.DateField(help_text='Date de sortie du bilan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'EXPERT_COMPTABLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='bilans_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bilan',
                'verbose_name_plural': 'Bilans',
                'ordering': ['-created_at'],
            },
        ),
    ]
