# Generated by Django 5.1.6 on 2025-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_category_bilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='original_image',
            field=models.ImageField(blank=True, help_text='Image originale du bilan', null=True, upload_to='bilans/original/'),
        ),
        migrations.AddField(
            model_name='bilan',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Fichier PDF du bilan', null=True, upload_to='bilans/pdf/'),
        ),
    ]
