# Generated by Django 5.1.6 on 2025-08-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_bill_items_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at']},
        ),
    ]
