# Generated by Django 5.1.6 on 2025-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_alter_facture_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for non-client factures (water, electricity, purchase)', null=True, upload_to='facture_images/'),
        ),
        migrations.AddField(
            model_name='facture',
            name='pdf_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='facture_pdfs/'),
        ),
    ]
