# Generated by Django 5.1.6 on 2025-04-26 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0007_facture_image_facture_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 11, 16, 43, 8, 101786, tzinfo=datetime.timezone.utc)),
        ),
    ]
