# Generated by Django 5.1.6 on 2025-04-26 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_alter_facture_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
    ]
