# Generated by Django 5.1.6 on 2025-04-27 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0009_alter_facture_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='file_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facture',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='predicted_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client Facture'), ('ELECTRICITY', 'Electricity Facture'), ('WATER', 'Water Facture'), ('PURCHASE', "Facture d'achat")], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='processing_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='facture',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 5, 12)),
        ),
    ]
