# Generated by Django 5.1.6 on 2025-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0010_facture_file_metadata_facture_needs_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='predicted_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client Facture'), ('ELECTRICITY', 'Electricity Facture'), ('WATER', 'Water Facture'), ('PURCHASE', 'Purchase Facture')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('pending_review', 'Pending Review')], default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'Client Facture'), ('ELECTRICITY', 'Electricity Facture'), ('WATER', 'Water Facture'), ('PURCHASE', 'Purchase Facture')], default='CLIENT', max_length=12),
        ),
    ]
