# Generated by Django 5.1.6 on 2025-04-27 18:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0011_alter_facture_predicted_type_alter_facture_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
