# Generated by Django 5.1.6 on 2025-04-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0014_alter_facture_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='facture_images/'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('pending_review', 'Pending Review')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'Client Facture'), ('ELECTRICITY', 'Electricity Facture'), ('WATER', 'Water Facture'), ('PURCHASE', 'Purchase Facture')], default='CLIENT', max_length=20),
        ),
    ]
