# Generated by Django 5.1.6 on 2025-05-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=0, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150),
            preserve_default=False,
        ),
    ]
