# Generated by Django 5.1.6 on 2025-06-02 21:14

import datetime
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLIENT', 'Client Facture'), ('ELECTRICITY', 'Electricity Facture'), ('WATER', 'Water Facture'), ('PURCHASE', 'Purchase Facture')], default='CLIENT', max_length=20)),
                ('predicted_type', models.CharField(blank=True, choices=[('CLIENT', 'Client Facture'), ('ELECTRICITY', 'Electricity Facture'), ('WATER', 'Water Facture'), ('PURCHASE', 'Purchase Facture')], max_length=12, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_metadata', models.JSONField(blank=True, default=dict)),
                ('processing_metadata', models.JSONField(blank=True, default=dict)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=datetime.date(2025, 6, 17))),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('pending_review', 'Pending Review')], default='unpaid', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('payment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('qr_verified', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='facture_images/')),
                ('pdf_file', models.FileField(blank=True, editable=False, null=True, upload_to='facture_pdfs/')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
