# Generated by Django 5.1.6 on 2025-06-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='pdf_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for the PDF', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the PDF', null=True),
        ),
    ]
