# Generated by Django 5.1.6 on 2025-06-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-created_at']},
        ),
    ]
