# Generated by Django 5.1.6 on 2025-06-03 19:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_initial'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 6, 18)),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['type', 'status'], name='factures_fa_type_1a141e_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client', 'status'], name='factures_fa_client__b189f6_idx'),
        ),
    ]
