# Generated by Django 5.1.6 on 2025-06-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_alter_facture_client_alter_facture_facture_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
