# Generated by Django 5.1.6 on 2025-04-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_alter_facture_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'Client Facture'), ('ELECTRICITY', 'Electricity Facture'), ('WATER', 'Water Facture'), ('PURCHASE', "Facture d'achat")], default='CLIENT', max_length=12),
        ),
    ]
