# Generated by Django 5.1.6 on 2025-04-20 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_alter_facture_client'),
        ('products', '0003_remove_product_name_product_estimation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='products.product'),
        ),
    ]
