# Generated by Django 5.1.6 on 2025-08-15 16:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('excellente', 'Excellente'), ('bonne', 'Bonne'), ('moyenne', 'Moyenne'), ('mauvaise', 'Mauvaise')], default='moyenne', max_length=10)),
                ('origine', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity in kg')),
                ('olive_oil_volume', models.DecimalField(blank=True, decimal_places=3, help_text='Calculated olive oil volume in liters', max_digits=10, null=True)),
                ('total_waste_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Total waste in kg', max_digits=10, null=True)),
                ('waste_vendus_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Sold waste in kg', max_digits=10)),
                ('waste_non_vendus_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Unsold waste in kg', max_digits=10, null=True)),
                ('waste_vendus_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Revenue from sold waste in DT', max_digits=10)),
                ('payement', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('done', 'Done'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('estimation_time', models.PositiveIntegerField(default=15, help_text='Estimated processing time in minutes')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['end_time'],
            },
        ),
    ]
