# Generated by Django 5.1.6 on 2025-07-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='olive_oil_volume',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Calculated olive oil volume in liters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity in kg'),
        ),
    ]
