# Generated by Django 5.1.6 on 2025-03-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_description_product_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
