# Generated by Django 5.1.6 on 2025-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('done', 'Done'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
