# Generated by Django 5.1.6 on 2025-08-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_olive_oil_volume_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_waste_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total waste in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='waste_non_vendus_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Unsold waste in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='waste_vendus_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Sold waste in kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='waste_vendus_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue from sold waste in DT', max_digits=10),
        ),
    ]
