# Generated by Django 5.1.6 on 2025-08-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_fix_waste_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='waste_non_vendus_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Automatically calculated unsold waste in kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='waste_vendus_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Automatically calculated sold waste in kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='waste_vendus_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated revenue from sold waste in DT', max_digits=10, null=True),
        ),
    ]
