# Generated by Django 5.1.6 on 2025-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_waste_non_vendus_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ml_olive_type',
            field=models.CharField(blank=True, help_text='ML mapped olive type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_predicted_employees',
            field=models.PositiveIntegerField(blank=True, help_text='ML predicted number of employees needed', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_predicted_energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ML predicted energy consumption in kWh', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_predicted_processing_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ML predicted processing time in hours', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_predicted_water_liters',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='ML predicted water consumption in liters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_prediction_generated',
            field=models.BooleanField(default=False, help_text='Whether ML predictions have been generated'),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_prediction_timestamp',
            field=models.DateTimeField(blank=True, help_text='When ML predictions were last generated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ml_source_region',
            field=models.CharField(blank=True, help_text='ML detected source region', max_length=20, null=True),
        ),
    ]
