# Generated by Django 5.1.6 on 2025-08-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_ml_olive_type_product_ml_predicted_employees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='origine',
            new_name='source',
        ),
    ]
