# Generated by Django 5.1.6 on 2025-04-07 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factures', '0002_facture_payment_uuid_facture_qr_code_and_more'),
        ('products', '0002_product_photo'),
        ('users', '0004_customuser_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.client')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='factures.facture')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='products.product')),
            ],
        ),
    ]
