# Generated by Django 5.1.6 on 2025-03-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TUN', max_length=3)),
                ('status', models.CharField(default='requires_payment_method', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='factures.facture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
