# Generated by Django 5.1.6 on 2025-06-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='filenmame',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='monatant',
            new_name='montant',
        ),
    ]
