# Generated by Django 5.1.6 on 2025-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CLIENT', 'Client'), ('COMPTABLE', 'Comptable'), ('EMPLOYEE', 'Employé')], default='CLIENT', max_length=10),
        ),
    ]
