# Generated by Django 5.1.6 on 2025-06-16 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FCM Token updated at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive push notifications', verbose_name='Notifications enabled'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', max_length=255, null=True, verbose_name='FCM Device Token'),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255, unique=True, verbose_name='FCM Device Token')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Name')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'unique_together': {('user', 'fcm_token')},
            },
        ),
    ]
