# Generated by Django 5.1.6 on 2025-06-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_fcm_token_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
