# Generated by Django 5.1.6 on 2025-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default.png', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
