# Generated by Django 5.1.6 on 2025-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive email notifications', verbose_name='Email notifications enabled'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive push notifications', verbose_name='Push notifications enabled'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive SMS notifications', verbose_name='SMS notifications enabled'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True, verbose_name='FCM Device Token'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive notifications', verbose_name='Notifications enabled'),
        ),
    ]
