# Generated by Django 5.1.6 on 2025-04-20 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters (no numbers or symbols).', regex='^[a-zA-Z]+$')]),
        ),
    ]
