# Generated by Django 5.1.6 on 2025-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_photo_alter_client_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
