# Generated by Django 5.1.6 on 2025-06-30 08:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, help_text='Phone number in international format (+countrycode + number) or 8 digits for legacy format', max_length=20, null=True, validators=[users.models.validate_international_phone]),
        ),
    ]
