# Generated by Django 5.1.6 on 2025-04-23 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, validators=[django.core.validators.RegexValidator(message='Username must contain only letters (no numbers or symbols).', regex='^[a-zA-Z]+$')]),
        ),
    ]
