# Generated by Django 5.1.6 on 2025-08-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_failed_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_changed_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_history',
        ),
    ]
